analytics/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from analytics import settings
from head import views
from head.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('head.urls')),  # http://127.0.0.1:8000/
    path('users/', include('users.urls', namespace="users")),  # http://127.0.0.1:8000/
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = "Site administration"
admin.site.index_title = "File analytics"

head/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'), # http://127.0.0.1:8000/
    path('about/', views.about, name='about'), # http://127.0.0.1:8000/about/
    path('head/', views.head, name='head'), # http://127.0.0.1:8000/head/
    path('category/', views.categories, name='categories'), # http://127.0.0.1:8000/category
    path('category/<slug:cat_slug>/', views.show_category, name='cats_id'), # http://127.0.0.1:8000/category/1/
    path('registration/', views.registration, name='registration'), # http://127.0.0.1:8000/registration
    path('login/', views.authorization, name='login'), # http://127.0.0.1:8000/login
    path('<slug:url>/', views.start_page), # http://127.0.0.1:8000/1/
    path('theory/<slug:th_id>/', views.theory, name ='theory') # http://127.0.0.1:8000/theory/stats
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'), # http://127.0.0.1:8000/users:login
    path('logout/', LogoutView.as_view(), name='logout'),# http://127.0.0.1:8000/users:logout
    path('register/', views.RegisterUser.as_view(), name='register'),
]

templates/base.html
{% load static %}
{% load head_tags %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'head/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li><a href="{% url 'home' %}"></a></li>
{% for m in menu %}
	<li>
		<a href="{% url m.content %}">{{m.title}}</a></li>
{% endfor %}
				{% if user.is_authenticated %}
    <li class="last"> {{user.username}} | <a href="{% url 'users:logout' %}">Logout</a></li>
{% else %}
    <li class="last"><a href="{% url 'users:login' %}">Login</a> | <a href="{% url 'users:register' %}">Registration</a></li>
{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}

<table class="table-content" border=0 cellpadding="0" cellspacing="0">

<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		<li class="selected">Все категории анализа</li>
		{% get_theory as theory %}
		{% for t in theory%}
		<li><a href="{% url 'theory' t.title%}">{{t.content}}</a></li>
		{% endfor %}
	</ul>
</td>


<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
{% block content %}
<h1>{{title}}</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button></p>
</form>
{% endblock %}

<!-- Конец блока контента -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p></p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

templates/base111.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'head/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>